name: "Packagist API Fetch"
author: "Kai Kimera <mail@kai.kim>"
description: "GitHub Action to get Packagist API responses and save them to repository."
branding:
  icon: "anchor"
  color: "yellow"
inputs:
  git_repo:
    description: "Git Repository"
    required: true
  git_user:
    description: "Git User"
    required: true
  git_email:
    description: "Git E-mail"
    required: true
  git_token:
    description: "Git Token"
    required: true
  api_url_main:
    description: "Packagist API URL (MAIN)"
    required: true
    default: "https://packagist.org"
  api_url_repo:
    description: "Packagist API URL (REPO)"
    required: true
    default: "https://repo.packagist.org"
  api_dir:
    description: "Packagist API Local Directory"
    required: true
    default: "api/packagist"
  api_vendor:
    description: "Packagist API Vendor"
    required: true
  bot_info:
    description: "Bot Information"
    required: true
    default: "Email: mail@example.com"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.git_repo }}
    - ${{ inputs.git_user }}
    - ${{ inputs.git_email }}
    - ${{ inputs.git_token }}
    - ${{ inputs.api_url_main }}
    - ${{ inputs.api_url_repo }}
    - ${{ inputs.api_dir }}
    - ${{ inputs.api_vendor }}
    - ${{ inputs.bot_info }}
